insert into AIRPORT_MEETING_POINT(ID, NAME, DESCRIPTION) VALUES(1, 'Starbucks na WAW', 'Opis!');

insert into AIRPORTS(ID, CODE, NAME, LATITUDE, LONGITUDE, MEETING_POINT_ID) VALUES(1, 'WAW', 'Warsaw Chopin Airport', 52.159499362, 20.966996132, 1);
insert into AIRPORTS(ID, CODE, NAME, LATITUDE, LONGITUDE) VALUES(2, 'WMI', 'Warsaw Modlin Airport', 52.450664864, 20.650997396);
insert into AIRPORTS(ID, CODE, NAME, LATITUDE, LONGITUDE) VALUES(3, 'SIN', 'Singapore Changi Airport', 1.345010, 103.983208);
insert into AIRPORTS(ID, CODE, NAME, LATITUDE, LONGITUDE) VALUES(4, 'AAA', 'Anaa Airport', -17.3489, -145.513);
insert into AIRPORTS(ID, CODE, NAME, LATITUDE, LONGITUDE) VALUES(5, 'AAB', 'Arrabury Airport', -26.7, 141.05);



insert into JPA_TRAVELER_PROFILE(TRAVELER_ID, NATIONALITY, NICKNAME)
VALUES (1, 'PORTUGAL', 'Friendly mark');
insert into JPA_TRAVELER_PROFILE(TRAVELER_ID, NATIONALITY, NICKNAME)
VALUES (2, 'POLISH', 'Alan the funny guy');
insert into TRAVELER_LANGUAGES(TRAVELER_ID, LANGUAGES)
VALUES (1, 'ENGLISH');
insert into TRAVELER_LANGUAGES(TRAVELER_ID, LANGUAGES)
VALUES (1, 'POLISH');
insert into TRAVELER_LANGUAGES(TRAVELER_ID, LANGUAGES)
VALUES (2, 'POLISH');
insert into TRAVELER_LANGUAGES(TRAVELER_ID, LANGUAGES)
VALUES (2, 'ENGLISH');

